set nocompatible
filetype off

" If vundle isn't installed, we better install it.
if !isdirectory(expand("~/.vim/bundle/Vundle.vim/.git"))
    !git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
endif

" Include Vundle on the runtime path and initialize.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle should manage Vundle.
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'mbbill/undotree'
Plugin 'ctrlpvim/ctrlp.vim'
" End Plugins

call vundle#end()
filetype plugin indent on

" Persistent undo
set undofile
set undodir=~/.vim/undo

set undolevels=1000
set undoreload=10000

" Line Wrapping
set nowrap

" Line Numbering
set number

" Whitespace Management
set expandtab
set tabstop=4

" Syntax Highlighting
filetype on
filetype plugin on
syntax enable

" Searching
set incsearch
set hlsearch

" Disable auto-indentation.
set paste

" Coloring.
colorscheme desert

" Cleanup
set nohidden

" Setting smart case sensitivity for searching.
set ignorecase
set smartcase
