set nocompatible
filetype off

" Include Vundle on the runtime path and initialize.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle should manage Vundle.
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'wincent/command-t'

call vundle#end()
filetype plugin indent on

" Line Wrapping
set nowrap

" Line Numbering
set number

" Whitespace Management
set expandtab
set tabstop=4

" Syntax Highlighting
filetype on
filetype plugin on
syntax enable

" Searching
set incsearch
set hlsearch

" Cleanup
set nohidden
