autoload -U +X bashcompinit && bashcompinit

autoload -U promptinit && promptinit
autoload -U colors && colors

# Word styles.
autoload -U select-word-style
select-word-style bash

# Minimal color prompt.
export PROMPT_COLOR=cyan
export PS1="%{$fg[$PROMPT_COLOR]%}%n$reset_color@$fg[$PROMPT_COLOR]%m$reset_color:$fg[$PROMPT_COLOR]%~/$reset_color
$ "

# History configuration.
export HISTSIZE=1000000
export SAVEHIST=1000000
export HISTFILE=~/.history
setopt append_history
setopt extended_history
setopt hist_ignore_dups
zshaddhistory() { print -sr "${(z)1%%$'\n'}"; return 1 }

# Set up colors.
eval $(dircolors -b)

# Setting up interactive comments.
setopt INTERACTIVECOMMENTS

alias ll='ls -l'
alias ls='ls --color=auto'
alias docker="sudo docker"
