#!/bin/sh

set -e

sudo apt-get install -y docker.io
sudo apt-get install -y nodejs npm

# docker-compose
curl --silent -Lo docker-compose  https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m`
chmod +x docker-compose
sudo mv docker-compose /usr/local/bin/

# minikube
curl --silent -Lo minikube https://storage.googleapis.com/minikube/releases/v0.12.2/minikube-linux-amd64
chmod +x minikube
sudo mv minikube /usr/local/bin/

# kubernetes
curl --silent -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kubectl
chmod +x kubectl
sudo mv kubectl /usr/local/bin/
