#!/bin/bash

# We should fail if we encounter errors.
set -e
set -x

cd "$HOME"
local_directory="$HOME/local"
github_directory="$local_directory/github.com"

mkdir -p "$local_directory"
mkdir -p "$github_directory"

# Install utilities.
if [ -n "$(command -v yum)" ]; then
    sudo yum install -y git vim htop jq tmux zsh pkgconfig automake gcc zlib-devel pcre-devel xz-devel gcc make
elif [ -n "$(command -v apt-get)" ]; then
    sudo apt-get install -y git vim htop jq tmux zsh automake pkg-config libpcre3-dev zlib1g-dev liblzma-dev gcc make libltdl7
fi

# Pull down GitHub projects.
projects=( "robbyrussell/oh-my-zsh" "trironkk/Home" "junegunn/fzf" "ggreer/the_silver_searcher" )
for project in "${projects[@]}"
do
    project_directory="$github_directory/$project"
    mkdir -p "$project_directory"
    if [ ! -e "$project_directory/.git/" ]; then
         git clone "https://github.com/$project" "$project_directory"
    fi
done

# Symlink projects into their default locations.
if [ ! -e ".oh-my-zsh" ]; then
    ln -s "$github_directory/robbyrussell/oh-my-zsh" ".oh-my-zsh"
fi
if [ ! -e ".fzf" ]; then
    ln -s "$github_directory/junegunn/fzf" ".fzf"
fi

# Install vim-plug.
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install oh-my-zsh.
"$github_directory/robbyrussell/oh-my-zsh/tools/install.sh"

# Install fzf.
"$github_directory/junegunn/fzf/install" --bin

# Install ag.
cd "$github_directory/ggreer/the_silver_searcher/"
./build.sh
sudo make install

# Install golang.
rm -rf "$local_directory/go"
go_release="go1.9.2.linux-amd64.tar.gz"
curl "https://dl.google.com/go/$go_release" > "/tmp/$go_release"
tar -xvf "/tmp/$go_release" -C "$local_directory"
rm "/tmp/$go_release"

# Install docker.
docker_release="docker-ce_17.12.0~ce-0~debian_amd64.deb"
curl "https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/$docker_release" > "/tmp/$docker_release"
sudo dpkg -i "/tmp/$docker_release"
rm "/tmp/$docker_release"

# We should run this from the working directory of this script.
cd $(readlink -f $(dirname "$0"))

# Create links of all our dot files.
dotfiles=$(find "$github_directory/trironkk/Home/dotfiles/" -type f)
for dotfile in $dotfiles
do
    # Derive the name of the file.
    name=.$(basename "$dotfile")

    # If the file and is a real file, back it up.
    if [ -f "$HOME/$name" ]; then
        mv "$HOME/$name" "$HOME/$name.old"
    fi

    # If the file is still there, it's a symlink. Remove it.
    rm -f "$HOME/$name"

    # Create a symlink.
    ln -s "$(readlink -f "$dotfile")" "$HOME/$name"
done

# Install vim plugins.
vim +PlugInstall +qall

# Set up git.
# Apparently git defaults to using 'vi' instead of 'vim', causing some
# unpleasant warnings when writing commit messages. Let's use 'vim'
# instead.
git config --global core.editor vim
git config --global user.email "trironk@gmail.com"
git config --global user.name "trironkk"
