#!/bin/sh

set -e

sudo apt-get install -y docker.io
sudo apt-get install -y nodejs npm

# docker-compose
curl -# -Lo docker-compose  https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m`
chmod +x docker-compose
sudo mv docker-compose /usr/local/bin/

# minikube
curl -# -Lo minikube https://storage.googleapis.com/minikube/releases/v0.12.2/minikube-linux-amd64
chmod +x minikube
sudo mv minikube /usr/local/bin/

# virtualbox
echo 'deb http://httpredir.debian.org/debian/ jessie main contrib' | sudo tee -a /etc/apt/sources.list
sudo apt-get update
sudo apt-get install -y virtualbox

# set up an rsa identity
if [[ ! -f '~/.ssh/id_rsa' ]]; then
  ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa -C "trironk@gmail.com"
  eval "$(ssh-agent -s)"
  ssh-add ~/.ssh/id_rsa
fi

# install gcloud
curl -# -Lo install_google_cloud_sdk.bash 'https://dl.google.com/dl/cloudsdk/channels/rapid/install_google_cloud_sdk.bash'
chmod +x install_google_cloud_sdk.bash
rm -rf ~/google-cloud-sdk
./install_google_cloud_sdk.bash --disable-prompts
rm install_google_cloud_sdk.bash
sudo apt-get remove google-cloud-sdk

# gcloud components
gcloud components install alpha
gcloud components install beta
gcloud components install docker-credential-gcr
gcloud components install kubectl
