#!/bin/sh

# We should fail if we encounter errors.
set -e

# We should run this from the working directory of this script.
cd $(readlink -f $(dirname "$0"))

# Create links of all our dot files.
for dotfile in $(find "dotfiles/" -type f); do
    # Derive the name of the file.
    name=.$(basename "$dotfile")

    # If the file already exists...
    if [ -e ~/$name ]; then
        if [ -h ~/$name ]; then # If it's a symlink, remove it.
            rm ~/$name
        else # Otherwise, back it up.
            mv ~/$name ~/$name.old
        fi
    fi

    # Create a symlink.
    ln -s $(readlink -f "$dotfile") ~/$name
done

#########################
# Software Installation #
#########################

if [ -n "$(command -v yum)" ]; then
    # General utilities.
    sudo yum install -y htop
    sudo yum install -y jq
    sudo yum install -y tmux
    sudo yum install -y zsh
fi

if [ -n "$(command -v apt-get)" ]; then
    # General utilities.
    sudo apt-get install -y htop
    sudo apt-get install -y jq
    sudo apt-get install -y tmux
    sudo apt-get install -y zsh
fi

###########################
# Vim Plugin Installation #
###########################
if [ ! -e ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall

#####################
# Git Configuration #
#####################

# Apparently git defaults to using 'vi' instead of 'vim', causing some
# unpleasant warnings when writing commit messages. Let's use 'vim'
# instead.
git config --global core.editor vim
git config --global user.email "trironk@gmail.com"
git config --global user.name "trironkk"
